# Generated by Django 5.1.1 on 2024-09-11 18:20

import api_manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manga', '0002_manga_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='releases',
            new_name='release',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(to='api_manga.genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='background',
            field=models.ImageField(blank=True, upload_to=api_manga.models.dynamic_background_upload_to),
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(blank=True, upload_to=api_manga.models.dynamic_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='manga',
            name='release',
            field=models.ManyToManyField(blank=True, to='api_manga.release'),
        ),
    ]
