# Generated by Django 5.1.1 on 2024-09-12 17:58

import api_manga.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manga', '0003_rename_tags_tag_rename_authors_manga_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('volume', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('archive', models.FileField(upload_to=api_manga.models.dynamic_archive_upload_to)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_manga.manga')),
            ],
        ),
    ]
